### PR TITLE
Add support for iOS applications serving a webpage inside WKWebView 

### PR DESCRIPTION
**Pull request by cbxp**
Solves an issue in the twilio-video library: [https://github.com/twilio/twilio-video.js/issues/1364](https://github.com/twilio/twilio-video.js/issues/1364)

The following error is caused by [getSdpFormat()](https://github.com/twilio/twilio-webrtc.js/blob/3081a11ad9d2be748df1fc07a96e51ac649b773e/lib/util/sdp.js#L89) which is not able to guess the browser if a webpage is rendered inside WKWebView in an iOS application.
```
Calling setRemoteDescription with an RTCSessionDescription of type "answer" failed with the error "Failed to set remote answer sdp: The order of m-lines in answer doesn't match order in offer. Rejecting answer.
```

**Contributing to Twilio**

> All third-party contributors acknowledge that any contributions they provide will be made under the same open-source license that the open-source project is provided under.

- [X] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by noahmehl** [comment]
@manjeshbhargav Would it be possible to review this please?

**Comment by ac1dev** [comment]
@manjeshbhargav Are you planning to review this? It's very important for many of us.

**Comment by shaun-nunns** [comment]
Please could this be reviewed? 

The changes are straightforward and would be a big benefit to users of the platform

**Comment by lu-roth** [comment]
+1

**Comment by dcoughlin** [comment]
+1

**Comment by lu-roth** [comment]
Asking once again to review please 👍

**Comment by dfox288** [comment]
We patched this in our own fork and it works fine. An official release would be highly appreciated

+1

**Comment by lukewarlow** [comment]
Hate to do these kind of +1 comments, but if this is a blocker in supporting other browsers on iOS (all of which are WKWebViews) it would be much appreciated if it could be reviewed and merged.

**Comment by SergeyPoznyakAkvelon** [comment]
For anyone who needs it now there is a workaround:

When initializing WKWebView add this code:

```swift
if let ua = webView.value(forKey: "userAgent") as? String {
    webView.customUserAgent = ua + " Safari"
}
```

This will trick twilio-video.js into thinking it's running in normal Safari.

**Comment by PikaJoyce** [comment]
Hi everyone!

Thank you for all of your feedback and your patience with us. We have heard you and have merged [VIDEO-8374](https://github.com/twilio/twilio-webrtc.js/pull/149) with @cbxp's suggestions and are in the process of releasing some time in the near future! 

I will now be closing this pull request.

Thank you all once again!
Joyce

**Pull request closed without merging**
